version: 0.2

env:
  secrets-manager:
    DOCKER_PASSWORD: arn:aws:secretsmanager:us-east-1:786370333307:secret:dev/docker/cred-83lk6X:password

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - mvn clean
      - echo $HELLO
  build:
    commands:
      - mvn -Dmaven.test.skip=true -Dmaven.test.failure.ignore=true package
      - echo build
  post_build:
    commands:
      - mvn deploy -Ddocker-tag=7 -Dpassword=$DOCKER_PASSWORD -Dusername=jbowo
      - echo skipping deploy
#reports:
#  arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
#    files:
#      - "**/target/surefire-reports/TEST-*.xml"
#    base-directory: 'target/tests/reports'
#    discard-paths: no

artifacts:
  files:
    - PropertyProject/target/*.jar
