version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - mvn clean
      - echo $HELLO
  build:
    commands:
      - mvn -Dmaven.test.skip=true -Dmaven.test.failure.ignore=true package
      - echo build
  post_build:
    commands:
      - mvn deploy -Ddocker-tag=$DOCKER_TAG -Dpassword=$DOCKER_PASSWORD
      - echo post_build
#reports:
#  arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
#    files:
#      - "**/target/surefire-reports/TEST-*.xml"
#    base-directory: 'target/tests/reports'
#    discard-paths: no

artifacts:
  files:
    - PropertyProject/src/main/resources/Propertee.jar
